ktor:
  development: true
  deployment:
    port: 8080
    host: "127.0.0.1"
    watch:
      - classes
      - resources

#menu:
  #repository:
   # test: inmemory
    #prod: postgres
    #psql:
     # password: password
      #schema: menu
      #url: jdbc:postgresql://localhost:5432/menu
      #user: postgres