ktor:
  development: true
  deployment:
    host: "127.0.0.1"
    watch:
      - classes
      - resources

menu:
  repository:
    test: inmemory
    prod: postgres
    psql:
      password: password
      schema: menu
      url: "jdbc:postgresql://localhost:5433/menu"
      user: postgres
  jwt:
    secret: "secret"
    issuer: "NVSosnina"
    audience: "qr-menu-users"
    realm: "qrmenu"
    clientId: "qr-menu-service"